name: Main Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    NODE_VERSION: 14

jobs:
    lint:
        name: Lint JS
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install --frozen-lockfile
            - run: yarn lint

    test:
        name: Run Functional Tests
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install --frozen-lockfile
            - run: yarn test:ui:run

    build & deploy:
        name: Build React
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: yarn install --frozen-lockfile
            - run: yarn build

        name: Deploy to Netlify
        timeout-minutes: 3
        uses: nwtgck/actions-netlify@v1.2
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: './build'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
